### ISSUE TITLE
I can't compile this file in MSVC

### ISSUE THREAD

**Issue by TsVan1** [mrdcvlsc/ChaCha20-Poly1305#23]
Hello, when I was searching for chacha20-ploy305 encryption, I saw your code on GitHub and thought it was great, but I couldn't compile this file in my own VS2022 MSVC environment.

**Comment by mrdcvlsc** [comment]
I don't personally use Visual Studio/`VS2022 MSVC` as my environment, and I haven't tested/implemented CI for this old project with `VS2022 MSVC` in GitHub Actions. Therefore, I don't have a clear idea of what might be wrong in your case. However, **I might be able to assist you if you provide the error messages, compilation errors, and details of what's going wrong**.

Although I'm also planning to add CI in GitHub Actions for various MSVC builds in the future. This could potentially address your question, but you'll need to wait for that implementation. For now, I suggest showing me the compilation errors you're encountering.

-----

I would have some questions too: Are you using the header mode?:

```c++
#include "Header-Mode-Chaha20-Poly1305.hpp"
```

Or are you building with CMake static lib?

**Comment by xie96808** [comment]
It seems the program failed to recognize my MSVC on windows:
![image](https://github.com/mrdcvlsc/ChaCha20-Poly1305/assets/66951589/600f6346-3c3b-401e-ac14-0d701045e3a0)

How can I fix it?

**Comment by mrdcvlsc** [comment]
@xie96808 and @TsVan1 you guys are both using MSVC and I remembered just now I think you guys can use this library by defining a `_PURE_CPP` macro.

You guys can directly define it in your main.cpp files at the very top:

```c++
#define _PURE_CPP
```

**Or** declare/add it to your Visual Studio IDE (_I don't know how to do this exactly since I don't use windows and MSVC but maybe a quick google search on how to define macro will do for you guys_).

This will use the pure C++ implementation of the `uint320`.

**Comment by mrdcvlsc** [comment]
> @xie96808 and @TsVan1 you guys are both using MSVC and I remembered just now I think you guys can use this library by defining a `_PURE_CPP` macro.
> 
> You guys can directly define it in your main.cpp files at the very top:
> 
> ```c++
> #define _PURE_CPP
> ```
> 
> **Or** declare/add it to your Visual Studio IDE (_I don't know how to do this exactly since I don't use windows and MSVC but maybe a quick google search on how to define macro will do for you guys_).
> 
> This will use the pure C++ implementation of the `uint320`.

@xie96808 and @TsVan1 could you guys comment here if this solution works for you in MSVC?

**Comment by xie96808** [comment]
This solution(define a _PURE_CPP macro) still doesn't work in MSVC. Actually the key error of the project is as follow:

![image](https://github.com/mrdcvlsc/ChaCha20-Poly1305/assets/66951589/c0e110e3-51a8-45ad-ae86-e3680cf593c0)

It seems the project cannot execute the "#if (__MINGW64__ || MINGW64)" macro, and this error maybe the main reason of failing to compile in MSVC.
Thx to ur attention, I'm trying to work it out in recent days : )

**Comment by mrdcvlsc** [comment]
@TsVan1 and @xie96808, could you please try the new commit now (#24) if you guys have time?

**Download first the new submodule after pulling/cloning the repository with the command:**
```
git submodule update --init --recursive
```

The downside of this update is that I've dropped the support for older versions of C++. This library now only supports C++20 and above, so you won't be able to use it if you're compiling with an older version of C++.

- I've now replaced the old `uint320` with a new [epi::uint320_t](https://github.com/mrdcvlsc/extended-precision-integers).

- Fixing the old `uint320` was a pain because the pure C++ implementation uses the type `__uint128_t` which is actually GCC and Clang specific.

- I also removed the inline assembly for GCC and Clang compilers, I believe I didn't do a great job implementing it and I think it didn't offer significant speed ups (will benchmark later).

Feel free to reply If you guys are still having problems

**Comment by xie96808** [comment]
Sry for replying late for having a national vacation(the Dragon Boat Festival) these days. I'll checkout the latest branch first and give a feed back afterwards.

**Comment by xie96808** [comment]
Delighted to see there are NO compiling problem now! 
Yet it seems the code can be only compiled under C++ 20 standard: 
![image](https://github.com/mrdcvlsc/ChaCha20-Poly1305/assets/66951589/74152d16-87d4-4023-bcfb-fd497ac20da1)
Currently I am only familiar with C++ 14 standard lol. Thx for your attention on my problem!
